services:
  - type: worker
    name: pharmacy-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8052020403:AAGViRAGSm1qpZw_-hnNYy8bnXjRZFRdYnc
      - key: ADMIN_IDS
        value: 1857844289
      - key: DB_PATH
        value: bot.db
