services:
  - type: worker
    name: pharmacy-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: <your-bot-token>
      - key: ADMIN_IDS
        value: <admin-id>
      - key: DB_PATH
        value: bot.db
